project:
  type: website
  output-dir: docs

website:
  title: "EDS 411"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Winter 411A"
        menu: 
          - 411a_winter/411a_overview.qmd
          - week1.qmd 
          - week2.qmd      
          - week3.qmd 
          - week4.qmd
          - week5.qmd
          - week6.qmd
          - week7.qmd
          - week8.qmd
          - week10.qmd
      - text: "Spring 411B"
        menu:    
          - 411b_spring/411b_week1.qmd       
      - href: resources.qmd
        text: Resources
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



