project:
  type: website
  output-dir: docs

website:
  title: "EDS 411A"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly materials"
        menu: 
          - week1.qmd 
          - week2.qmd       
      - href: resources.qmd
        text: Resources
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



